# -*- coding: utf-8 -*-
"""TRAIN MODELS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZyNH6FFSLSkkk_wh9xxFzQ2RwAO1KQCE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

df = pd.read_csv('/content/heart.csv')

df.sample(7)

df.shape

print(f'Total Rows in heart data : {df.shape[0]}')
print(f'Total Columns in heart data : {df.shape[1]}')

X = df.iloc[: , :-1]
y = df.iloc[: , -1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=41)

len(X_train) , len(y_train)

len(X_test),len(y_test)

"""Desision tree

"""

from sklearn.tree import DecisionTreeClassifier
reg_dt = DecisionTreeClassifier(criterion='entropy') # ID3(Iterative Dichrotomizer 3)
reg_dt.fit(X_train,y_train)

# Decision Tree Train Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Train Data confusion matrix was : {confusion_matrix(y_train,reg_dt.predict(X_train))}')
print(f'Train Accuracy was : {accuracy_score(y_train,reg_dt.predict(X_train))}')
print(f'Classification report was : {classification_report(y_train,reg_dt.predict(X_train))}')

# Decision Tree Test Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Test Data confusion matrix was : {confusion_matrix(y_test,reg_dt.predict(X_test))}')
print(f'Test Accuracy was : {accuracy_score(y_test,reg_dt.predict(X_test))}')
print(f'Classification report was : {classification_report(y_test,reg_dt.predict(X_test))}')

"""Random forest classifier

"""

from sklearn.ensemble import RandomForestClassifier
reg_rf = RandomForestClassifier(n_estimators=11,criterion='entropy')
reg_rf.fit(X_train,y_train)

#Random Forest Train Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Train Data confusion matrix was : {confusion_matrix(y_train,reg_rf.predict(X_train))}')
print(f'Train Accuracy was : {accuracy_score(y_train,reg_rf.predict(X_train))}')
print(f'Classification report was : {classification_report(y_train,reg_rf.predict(X_train))}')

# Random Forest Test Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Test Data confusion matrix was : {confusion_matrix(y_test,reg_rf.predict(X_test))}')
print(f'Test Accuracy was : {accuracy_score(y_test,reg_rf.predict(X_test))}')
print(f'Classification report was : {classification_report(y_test,reg_rf.predict(X_test))}')

"""Adaboost"""

from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

reg_ad = AdaBoostClassifier(estimator=lr,n_estimators=11,learning_rate=1.0)
reg_ad.fit(X_train,y_train)

print(f'Test Accuracy : {accuracy_score(y_test,reg_ad.predict(X_test))}')

odd_values = np.arange(3,101,2)
odd_values

for i in odd_values:
  reg_ad = AdaBoostClassifier(estimator=lr,n_estimators=i,learning_rate=1.0)
  reg_ad.fit(X_train,y_train)
  print(f'Test Accuracy with {i} : LR and learning rate : {1.0}: {accuracy_score(y_test,reg_ad.predict(X_test))}')

values = np.random.random((1,5)).ravel()
values

num_of_lr = []
lr_values = []
final_acc = []

for i in odd_values:
  t = []
  test_acc = []
  for j in values:
    reg_ad = AdaBoostClassifier(estimator=lr,n_estimators=i,learning_rate=j)
    reg_ad.fit(X_train,y_train)
   # print(f'Test Accuracy with {i} : LR and learning rate : {j}: {accuracy_score(y_test,reg_ad.predict(X_test))}')
    test_acc.append(accuracy_score(y_test,reg_ad.predict(X_test)))
    t.append(j)
  final_acc.append(test_acc)
  lr_values.append([t])
  num_of_lr.append(i)

s = 0 # 0.86

p = 0
for k in final_acc:
  if max(k) > s:
    p = p + 1
    s = max(k)


print(f'Number of Logistic Regressions are : {num_of_lr[(p-1)]}')
print(f'Best Learning rate : {values[final_acc[p-1].index(s)]}')

"""Gradient Boosting

"""

from sklearn.ensemble import GradientBoostingClassifier
reg_gb = GradientBoostingClassifier(n_estimators=11,
                                    criterion='friedman_mse')
reg_gb.fit(X_train,y_train)

# Gradient Boosting Train Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Train Data confusion matrix was : {confusion_matrix(y_train,reg_gb.predict(X_train))}')
print(f'Train Accuracy was : {accuracy_score(y_train,reg_gb.predict(X_train))}')
print(f'Classification report was : {classification_report(y_train,reg_gb.predict(X_train))}')

# Gradient Boosting Test Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Test Data confusion matrix was : {confusion_matrix(y_test,reg_gb.predict(X_test))}')
print(f'Test Accuracy was : {accuracy_score(y_test,reg_gb.predict(X_test))}')
print(f'Classification report was : {classification_report(y_test,reg_gb.predict(X_test))}')

import xgboost as xgb
reg_xgb =xgb.XGBClassifier(n_estimators=11,criterion='friedman_mse')

reg_xgb.fit(X_train,y_train)

# Xtreme Gradient Boosting Train Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Train Data confusion matrix was : {confusion_matrix(y_train,reg_xgb.predict(X_train))}')
print(f'Train Accuracy was : {accuracy_score(y_train,reg_xgb.predict(X_train))}')
print(f'Classification report was : {classification_report(y_train,reg_xgb.predict(X_train))}')

# Xtreme Gradient Boosting Test Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Test Data confusion matrix was : {confusion_matrix(y_test,reg_xgb.predict(X_test))}')
print(f'Test Accuracy was : {accuracy_score(y_test,reg_xgb.predict(X_test))}')
print(f'Classification report was : {classification_report(y_test,reg_xgb.predict(X_test))}')

"""svm"""

from sklearn.svm import SVC
reg_svc = SVC(kernel='rbf')
reg_svc.fit(X_train,y_train)

# SVM Train Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Train Data confusion matrix was : {confusion_matrix(y_train,reg_svc.predict(X_train))}')
print(f'Train Accuracy was : {accuracy_score(y_train,reg_svc.predict(X_train))}')
print(f'Classification report was : {classification_report(y_train,reg_svc.predict(X_train))}')

# SVM Test Performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(f'Test Data confusion matrix was : {confusion_matrix(y_test,reg_svc.predict(X_test))}')
print(f'Test Accuracy was : {accuracy_score(y_test,reg_svc.predict(X_test))}')
print(f'Classification report was : {classification_report(y_test,reg_svc.predict(X_test))}')